name: fortune_client
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  flutter_signin_button: ^2.0.0
  badges: ^2.0.3
  flutter_staggered_animations: ^1.1.1
  flutter_chat_ui: ^1.6.5
  uuid: ^3.0.6
  mime: ^1.0.2
  path_provider: ^2.0.11
  open_filex: ^4.1.1
  google_sign_in: ^5.4.2
  freezed_annotation: ^2.2.0
  auto_route: ^5.0.2
  flutter_svg: ^1.1.6
  gap: ^2.0.1
  google_fonts: ^3.0.1
  sizer: ^2.0.15
  enum_to_string: ^2.0.1
  fluttertoast: ^8.1.1
  fimber: ^0.6.6
  device_preview: ^1.1.0

  # util
  json_serializable: ^6.5.4
  bottom_picker: ^2.0.1
  image_picker: ^0.8.6
  file_picker: ^5.2.4
  package_info_plus: ^3.0.2
  # package_info_plus: ^3.0.2 # バージョン管理

  # state management
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.1

  # networking
  dio: ^4.0.6
  retrofit: ^3.3.1
  steps_indicator: ^1.3.0

  # firebase
  firebase_auth: ^4.2.1
  firebase_core: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  freezed: ^2.2.0
  auto_route_generator: ^5.0.3
  retrofit_generator: ^4.2.0
  dependency_validator: any
  flutter_gen_runner: ^5.1.0+1

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  lineLength: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - stub/
    - assets/images/
    - assets/images/icons/
