name: fortune_client
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # util
  intl: any
  uuid: any
  device_preview: any
  google_fonts: any
  flutter_dotenv: any
  enum_to_string: any
  package_info_plus: any
  favorite_button: any
  badges: any
  # flutter_datetime_picker: any
  flutter_datetime_picker_plus: any

  # ui
  gap: any
  shimmer: any
  flutter_chat_ui: any
  dotted_border: any
  flutter_staggered_animations: any
  fluttertoast: any
  screen_loader: any
  loading_indicator: any
  flutter_expanded_tile: any


  # images
  lottie: any
  flutter_svg: any
  image_picker: any
  path_provider: any

  # camera & album
  file_picker: any
  permission_handler: any
  flutter_image_compress: any
  flutter_platform_widgets: any

  # generator
  json_serializable: any
  freezed_annotation: any
  riverpod_annotation: any

  # state management
  flutter_hooks: any
  hooks_riverpod: any

  # localization
  easy_localization: any

  # networking
  dio: ^5.1.1
  retrofit: any
  pretty_dio_logger: any
  connectivity_plus: any
  url_launcher: any

  # firebase
  firebase_auth: any
  firebase_core: any
  firebase_remote_config: any

  # sign in 
  google_sign_in: any
  sign_in_with_apple: any
  flutter_facebook_auth: any

  # storage
  shared_preferences: any

  # di
  get_it: any

  #logger
  logger: any

  # self made
  flutter_japanese_address_picker:
    git:
      url: https://github.com/daisukemaki1003/flutter-japanese-address-picker.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any
  build_runner: any
  flutter_lints: any
  freezed: any
  auto_route_generator: any
  retrofit_generator: any
  flutter_gen_runner: any
  dependency_validator: any
  riverpod_generator: any
  flutter_launcher_icons: any

flutter_gen:
  output: lib/gen/ 
  lineLength: 80 
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    # env
    - .env

    # stub
    - stub/
    
    # l10n
    - assets/l10n/
    
    # images
    - assets/icons/
    - assets/images/

    # animation
    - assets/animations/

flutter_launcher_icons:       
  android: true
  ios: true
  image_path: "assets/images/fortune_logo.png"